Module 6
vireah/react2023dk pull request #6
Opened 2023-10-22 15:10 UTC by vireah

2023-10-30 07:08 UTC, AndreiyMarkusheuski requested changes
Комменты добавлены

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/App.js
> +        // <MovieListPage></MovieListPage>
Почитсти потом все комменты, чтобы было легче читать за изменениями между модулями

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieDetails.js
> +        axios.get(`http://localhost:4000/movies/`+movieId, {
Лучше оберни всю функцию во что-то и в useEffect просто вызывай ее. Например getData/fetchData

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieDetails.js
> +            <>
Тут можно убрать фрагмент, потому что внутри итак один блок

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieDetails.js
>                          <h2>{movie.title}</h2>
Это все лучше деструктуризировать { imageUrl, release_date, genres ... } = movie

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieListPage.js
> +    const query = searchParams.get("query");
Лучше избегать рандомных string и запихнуть их в объвленный конст объект. query sortBy searchBy

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieListPage.js
> +    const query = searchParams.get("query");
Плюс все эти константы хранить в отдельном файле consts.js

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/MovieListPage.js
> +        const params = new URLSearchParams(location.search);
Тоже лучше все что внутри вынести в функцию и просто ее вызывать здесь

2023-10-30 07:08 UTC, AndreiyMarkusheuski commented on my-app/src/components/SearchBar.js
> +        navigate(`/?movies=&query=`+value+`&searchBy=title`);
У тебя здесь шаблонная строка, можно value итак вставить в нее без +
`/?movies=&query=${value}&searchBy=title`

2023-11-01 09:06 UTC, vireah commented on my-app/src/components/MovieDetails.js
> +            <>
fixed

2023-11-01 09:08 UTC, vireah commented on my-app/src/App.js
> +        // <MovieListPage></MovieListPage>
fixed

2023-11-01 09:14 UTC, vireah commented on my-app/src/components/MovieDetails.js
> +        axios.get(`http://localhost:4000/movies/`+movieId, {
fixed

2023-11-01 09:18 UTC, vireah commented on my-app/src/components/MovieListPage.js
> +        const params = new URLSearchParams(location.search);
fixed

2023-11-01 09:19 UTC, vireah commented on my-app/src/components/SearchBar.js
> +        navigate(`/?movies=&query=`+value+`&searchBy=title`);
fixed

2023-11-01 09:20 UTC, vireah commented on my-app/src/components/MovieDetails.js
>                          <h2>{movie.title}</h2>
fixed

2023-11-03 08:43 UTC, AndreiyMarkusheuski approved these changes

2023-11-03 09:39 UTC, merged